// DataSurvey.js
const periodeKegiatanMap = [
    {
      periode: "Bulanan",
      kegiatan: [
        "Pendataan survei perusahaan perkebunan bulanan",
        "Pendataan lapangan perusahaan peternakan",
        "Pendataan lapangan Laporan pemotongan ternak bulanan",
        "Pendataan lapangan perusahaan penangkapan ikan",
        "Survei VHTS Bulanan",
        "Survei Harga Perdagangan Besar",
        "Survei Harga Mesin dan Peralatan",
        "Survei Paket Komoditas Provinsi",
        "Survei Harga Konsumen Perdesaan (HKD)",
        "Survei Harga Produsen Perdesaan (HD)",
        "Updating Paket Komoditas HPS HPJ dan HPT",
        "Survei Harga Produsen (HP)",
        "Survei Harga Produsen Jasa (HPJ)",
        "Survei Harga Produsen T (HPT)",
        "Survei Harga Penggilingan Gabah (HPG)",
        "Survei Harga Beras di Penggilingan (HPBG)",
        "Survei IBS Bulanan",
        "Lainnya"
      ],
    },
    {
      periode: "Tahunan",
      kegiatan: [
        "Sakernas Februari",
        "Sakernas Agustus",
        "Susenas Maret",
        "Seruti Triwulan I",
        "Pendataan Potensi Desa (PODES)",
        "Survei Hortikultura dan Indikator Pertanian",
        "Sampel Survei Perusahaan Kehutanan",
        "STPIM (IBS Tahunan)",
        "Survei komoditas",
        "IMK Tahunan",
        "Survei Captive Power",
        "Survei Tahunan Perusahaan Air Bersih",
        "Survei Tahunan Perusahaan Gas",
        "Survei Tahunan Perusahaan Listrik",
        "Survei Tahunan Perusahaan Panas Bumi",
        "Survei Tahunan Perusahaan Penggalian Bahan Industri dan Konstruksi",
        "Survei Tahunan Perusahaan Pertambangan Migas",
        "Survei Tahunan Usaha Penggalian Bahan Industri dan Konstruksi",
        "Survei Tahunan Perusahaan Pertambangan Non Minyak dan Gas",
        "Survei Konstruksi Tahunan (SKTH)",
        "Pemutakhiran DPA",
        "Survei Ekonomi Pertanian (UPB & UTL)",
        "Pendataan Ekspor Diluar Dokumen Bea Cukai",
        "Survei Pola Distribusi Perdagangan",
        "Sampel Survei Ujicoba Integrasi Poldis, PAW, Profil Perdagangan dan Penyusunan Diagram Timbang Harga Perdagangan Besar",
        "PJ II/5",
        "PJ II/6",
        "Simoppel",
        "Udara III/1",
        "SAPB Jembatan Timbang",
        "SAPB Terminal",
        "SDT-Perusahaan",
        "Survei Pergudangan dan Aktivitas Penunjang Angkutan",
        "Updating Profil Pasar 2024",
        "Sampel BoQ Kabupaten/Kota",
        "Sampel BoQ Provinsi",
        "Survei Harga Kemahalan Konstruksi",
        "Survei Paket Komoditas SHKK",
        "Survei Indeks Kesejahteraan Petani (IKP)",
        "Survei Koperasi Simpan Pinjam",
        "Survei Pedagang Valuta Asing",
        "Survei Statistik Keuangan BUMD",
        "Survei Statistik Keuangan Pemerintah Realisasi Provinsi APBD",
        "Survei Karakteristik Usaha",
        "Survei E-Commerce",
        "Survei Daya Tarik Wisata (VDTW)",
        "Survei Jasa Akomodasi (VHTL)",
        "Survei Penyedia Makan Minum VREST UMB",
        "VREST UMK",
        "Updating Direktori Usaha/Perusahaan Ekonomi",
        "Indepth Study Sisnerling",
        "SKSJ",
        "SKNP",
        "SKLNP Tahunan",
        "SKPS",
        "SKSPPI",
        "Survei Disagregasi PMTB",
        "Lainnya"
      ],
    },
    {
      periode: "Triwulanan",
      kegiatan: [
        "Survei Triwulan (1,2,3,4) Perusahaan Air Bersih",
        "Survei Triwulan (1,2,3,4) Perusahaan Penggalian Bahan Industri dan Konstruksi",
        "Survei Harga Kemahalan Konstruksi",
        "SKLNPT Triwulanan",
        "SKTNP Barang",
        "SKTNP Jasa",
        "Lainnya"
      ],
    }
  ];
  
  export default periodeKegiatanMap;
  